language: nix
nix: 2.3.6
env:
  - EMACS_VERSION=26.3
  - EMACS_VERSION=27.1
  - EMACS_VERSION=27.2
cache:
  directories:
     - /nix/store
script:
   - glibcLocales=$(nix-build --no-out-link "<nixpkgs>" -A glibcLocales)
   - export LOCALE_ARCHIVE_2_27="${glibcLocales}/lib/locale/locale-archive"
   - yes yes | nix-build nix/emacs-${EMACS_VERSION}.nix --run '${emacs}/bin/emacs --batch -q -l counsel-edit-mode.el -l ert-runner'
language: nix
nix: 2.3.6
env:
  - EMACS_VERSION=26.3
  - EMACS_VERSION=27.1
  - EMACS_VERSION=27.2
script: nix-build nix/emacs-${EMACS_VERSION}.nix